In [1]:
import os
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [2]:
#Define paths
train_dir = 'C:/Users/Lindiway/MACHINE_LEARNING_2025/FEB-ML-25-Multi-Partner/Cnn_Rnn/fruits-360/Training'
test_dir = 'C:/Users/Lindiway/MACHINE_LEARNING_2025/FEB-ML-25-Multi-Partner/Cnn_Rnn/fruits-360/Test'

In [3]:
#Preprocessing Images - Rescaling and Expanding the Images 
#Initialize ImageDataGenerators
train_datagen = ImageDataGenerator(rescale=1./255, validation_split=0.3)
test_datagen = ImageDataGenerator(rescale=1./255)

In [4]:
train_generator = train_datagen.flow_from_directory(train_dir, target_size=(100, 100), batch_size=32, class_mode='binary', subset='training')
validation_generator = train_datagen.flow_from_directory(train_dir, target_size=(100, 100), batch_size=32, class_mode='binary', subset='validation')
test_generator = train_datagen.flow_from_directory(test_dir, target_size=(100, 100), batch_size=32, class_mode='binary')

Found 71863 images belonging to 200 classes.
Found 30693 images belonging to 200 classes.
Found 34155 images belonging to 199 classes.


In [5]:
from tensorflow.keras import layers, models

In [6]:
model = models.Sequential([
    layers.Conv2D(filters=16, kernel_size=(2, 2), activation='relu', input_shape=(100, 100, 3)),
    layers.MaxPooling2D((2,2)),

    
    layers.Conv2D(filters=32, kernel_size=(2, 2), activation='relu'),
    layers.MaxPooling2D((2,2)),

    layers.Conv2D(filters=64, kernel_size=(2, 2), activation='relu'),
    layers.MaxPooling2D((2,2)),

    layers.Dropout(0.3),
    layers.Flatten(),

    layers.Dense(150, activation='relu'),
    layers.Dropout(0.4),

    layers.Dense(1, activation='softmax'),
])


C:\Users\Lindiway\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [7]:
#Compiling the model
model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

In [8]:
#train the model
history = model.fit(train_generator, epochs=30, validation_data = validation_generator)

C:\Users\Lindiway\anaconda3\Lib\site-packages\keras\src\trainers\data_adapters\py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


Epoch 1/30


C:\Users\Lindiway\anaconda3\Lib\site-packages\keras\src\ops\nn.py:908: UserWarning: You are using a softmax over axis -1 of a tensor of shape (None, 1). This axis has size 1. The softmax operation will always return the value 1, which is likely not what you intended. Did you mean to use a sigmoid instead?
  warnings.warn(
C:\Users\Lindiway\anaconda3\Lib\site-packages\keras\src\losses\losses.py:33: SyntaxWarning: In loss categorical_crossentropy, expected y_pred.shape to be (batch_size, num_classes) with num_classes > 1. Received: y_pred.shape=(None, 1). Consider using 'binary_crossentropy' if you only have 2 classes.
  return self.fn(y_true, y_pred, **self._fn_kwargs)


2246/2246 ━━━━━━━━━━━━━━━━━━━━ 1667s 742ms/step - accuracy: 0.0035 - loss: 0.0000e+00 - val_accuracy: 0.0042 - val_loss: 0.0000e+00
Epoch 2/30
2246/2246 ━━━━━━━━━━━━━━━━━━━━ 1294s 576ms/step - accuracy: 0.0041 - loss: 0.0000e+00 - val_accuracy: 0.0042 - val_loss: 0.0000e+00
Epoch 3/30
2246/2246 ━━━━━━━━━━━━━━━━━━━━ 378s 168ms/step - accuracy: 0.0041 - loss: 0.0000e+00 - val_accuracy: 0.0042 - val_loss: 0.0000e+00
Epoch 4/30
2246/2246 ━━━━━━━━━━━━━━━━━━━━ 202s 90ms/step - accuracy: 0.0041 - loss: 0.0000e+00 - val_accuracy: 0.0042 - val_loss: 0.0000e+00
Epoch 5/30
2246/2246 ━━━━━━━━━━━━━━━━━━━━ 191s 85ms/step - accuracy: 0.0042 - loss: 0.0000e+00 - val_accuracy: 0.0042 - val_loss: 0.0000e+00
Epoch 6/30
2246/2246 ━━━━━━━━━━━━━━━━━━━━ 197s 88ms/step - accuracy: 0.0040 - loss: 0.0000e+00 - val_accuracy: 0.0042 - val_loss: 0.0000e+00
Epoch 7/30
2246/2246 ━━━━━━━━━━━━━━━━━━━━ 199s 89ms/step - accuracy: 0.0042 - loss: 0.0000e+00 - val_accuracy: 0.0042 - val_loss: 0.0000e+00
Epoch 8/30
2246/224

In [9]:
# Evaluate on test data
test_loss, test_accuracy = model.evaluate(test_generator)
print(f"\nTest Accuracy: {test_accuracy * 100:.2f}%")

1068/1068 ━━━━━━━━━━━━━━━━━━━━ 473s 443ms/step - accuracy: 0.0042 - loss: 0.0000e+00

Test Accuracy: 0.42%


In [10]:
# Predict and create confusion matrix
y_true = test_generator.classes
y_pred_prob = model.predict(test_generator)
y_pred = (y_pred_prob > 0.5).astype(int).reshape(-1)

   6/1068 ━━━━━━━━━━━━━━━━━━━━ 28s 27ms/step  

C:\Users\Lindiway\anaconda3\Lib\site-packages\keras\src\ops\nn.py:908: UserWarning: You are using a softmax over axis -1 of a tensor of shape (32, 1). This axis has size 1. The softmax operation will always return the value 1, which is likely not what you intended. Did you mean to use a sigmoid instead?
  warnings.warn(


1068/1068 ━━━━━━━━━━━━━━━━━━━━ 47s 43ms/step


In [12]:
# Confusion Matrix and Classification Report
from sklearn.metrics import classification_report, confusion_matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_true, y_pred))

print("\nClassification Report:")
print(classification_report(y_true, y_pred))


Confusion Matrix:
[[  0 231   0 ...   0   0   0]
 [  0 142   0 ...   0   0   0]
 [  0 154   0 ...   0   0   0]
 ...
 [  0 157   0 ...   0   0   0]
 [  0  80   0 ...   0   0   0]
 [  0  80   0 ...   0   0   0]]

Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       231
           1       0.00      1.00      0.01       142
           2       0.00      0.00      0.00       154
           3       0.00      0.00      0.00       235
           4       0.00      0.00      0.00       154
           5       0.00      0.00      0.00       201
           6       0.00      0.00      0.00       160
           7       0.00      0.00      0.00       241
           8       0.00      0.00      0.00       146
           9       0.00      0.00      0.00       157
          10       0.00      0.00      0.00       229
          11       0.00      0.00      0.00       228
          12       0.00      0.00      0.00       231
        

C:\Users\Lindiway\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Lindiway\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Lindiway\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
